export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_REQUEST_FAILURE = 'USER_REQUEST_FAILURE';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_TOKEN_SET = 'USER_TOKEN_SET';
